### ISSUE TITLE
Footer bg image location

### ISSUE THREAD

**Issue by lsetiawan** [BiG-CZ/notebook_data_demo#13]
@ocefpaf I just relized there's already a file called [`bg_footer.png`](https://github.com/BiG-CZ/notebook_data_demo/blob/master/webpage/jupyter_notebook_jekyll_theme/images/bg_footer.png) in `jupyter_notebook_jekyll_theme/images`. 

What if we rename [`background-trans.png`](https://github.com/BiG-CZ/notebook_data_demo/blob/master/webpage/jupyter_notebook_jekyll_theme/assets/background-trans.png) to `bg_footer.png` and place it in `jupyter_notebook_jekyll_theme/images`?

**Comment by ocefpaf** [comment]
My first thought was the same as the color variables, to preserve the original state of the theme, but now that I think about it it is not really worth it and can make the theme files overly complex with time. I will make the substitution.
