### ISSUE TITLE
notebook font is now smaller, kind of tiny

### ISSUE THREAD

**Issue by emiliom** [BiG-CZ/notebook_data_demo#19]
@ocefpaf the font used in the notebook content now seems pretty small. I don't think it was like that before, but I have no idea when the change may have happened.

I tested it on Firefox and Chrome, both on Ubuntu.

Can you look into it?

Example: https://big-cz.github.io/notebook_data_demo/notebooks/2017-06-24-odm2api_sample_fromsqlite/

**Comment by ocefpaf** [comment]
I noticed that too. I guess we are using an online font and it changed upstream. I'll check that and modify it.
